"""Generate documentation derived from public APIs and compatibility metadata."""

from __future__ import annotations

import argparse
import dataclasses
import difflib
import importlib
import inspect
import json
from collections import Counter
from collections.abc import Callable, Iterable, Mapping, Sequence
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
COMPATIBILITY_PATH = ROOT / "compatibility/rms-8.2.0.yaml"
GENERATED_NOTICE = "<!-- Generated by tools/generate_docs.py; do not edit. -->"
STATUS_ORDER = ("implemented", "experimental", "mapped", "unsupported", "deferred")
TIER_ORDER = ("A", "B", "C", "D")
API_MODULES = {
    ROOT / "docs/api/design.md": "holocron.design",
    ROOT / "docs/api/formula.md": "holocron.formula",
    ROOT / "docs/api/graphics.md": "holocron.graphics",
    ROOT / "docs/api/migration.md": "holocron.migration",
    ROOT / "docs/api/models.md": "holocron.models",
    ROOT / "docs/api/reporting.md": "holocron.reporting",
    ROOT / "docs/api/validation.md": "holocron.validation",
    ROOT / "docs/api/exceptions.md": "holocron.exceptions",
}


def _markdown_text(value: object) -> str:
    """Escape a value for a single Markdown table cell."""
    if value is None:
        return "—"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return text or "—"


def _code(value: object) -> str:
    if value is None:
        return "—"
    return f"`{str(value).replace('`', '')}`"


def _heading(value: str) -> str:
    return value.replace("_", " ").title()


def _signature(value: Callable[..., object] | type[object]) -> str:
    try:
        return str(inspect.signature(value, eval_str=True))
    except (NameError, TypeError, ValueError):
        try:
            return str(inspect.signature(value))
        except (TypeError, ValueError):
            return "(*args: object)"


def _docstring(value: object) -> str:
    text = inspect.getdoc(value)
    return text if text else "No public documentation is available."


def _public_members(value: type[object]) -> Iterable[tuple[str, object]]:
    for name, member in inspect.getmembers(value):
        if name.startswith("_"):
            continue
        if (
            isinstance(member, property)
            or inspect.isfunction(member)
            or inspect.ismethod(member)
        ):
            yield name, member


def _render_class(value: type[object]) -> list[str]:
    lines = [f"## `{value.__name__}`", "", "```python"]
    lines.append(f"class {value.__module__}.{value.__qualname__}{_signature(value)}")
    lines.extend(["```", "", _docstring(value), ""])

    if dataclasses.is_dataclass(value):
        fields = dataclasses.fields(value)
        if fields:
            lines.extend(["### Attributes", "", "| Name | Type |", "| --- | --- |"])
            for field in fields:
                lines.append(f"| `{field.name}` | `{field.type}` |")
            lines.append("")

    for name, member in _public_members(value):
        if isinstance(member, property):
            lines.extend(
                [
                    f"### `{name}`",
                    "",
                    _docstring(member.fget),
                    "",
                ]
            )
            continue
        lines.extend(
            [
                f"### `{name}{_signature(cast(Callable[..., object], member))}`",
                "",
                _docstring(member),
                "",
            ]
        )
    return lines


def _render_function(value: Callable[..., object]) -> list[str]:
    return [
        f"## `{value.__name__}{_signature(value)}`",
        "",
        _docstring(value),
        "",
    ]


def render_api_page(module_name: str) -> str:
    module = importlib.import_module(module_name)
    module_all = cast(Sequence[str], module.__all__)
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {_heading(module_name.rsplit('.', maxsplit=1)[-1])} API",
        "",
        _docstring(module),
        "",
        (
            f"Import public names from `{module_name}`. The signatures and "
            "docstrings below"
        ),
        "are generated from the installed source during `make docs-check`.",
        "",
    ]
    for name in module_all:
        value = getattr(module, name)
        if inspect.isclass(value):
            lines.extend(_render_class(value))
        elif inspect.isfunction(value):
            lines.extend(_render_function(cast(Callable[..., object], value)))
        else:
            lines.extend([f"## `{name}`", "", _docstring(value), ""])
    return "\n".join(lines).rstrip() + "\n"


def _load_compatibility() -> Mapping[str, object]:
    document: object = json.loads(COMPATIBILITY_PATH.read_text())
    if not isinstance(document, dict):
        raise TypeError("compatibility manifest must contain an object")
    return cast(Mapping[str, object], document)


def _capabilities(document: Mapping[str, object]) -> list[Mapping[str, object]]:
    raw_capabilities = document["capabilities"]
    if not isinstance(raw_capabilities, list):
        raise TypeError("compatibility capabilities must be a list")
    capabilities: list[Mapping[str, object]] = []
    for raw_capability in cast(list[object], raw_capabilities):
        if not isinstance(raw_capability, dict):
            raise TypeError("each compatibility capability must be an object")
        capabilities.append(cast(Mapping[str, object], raw_capability))
    return capabilities


def _render_capability_table(capabilities: Sequence[Mapping[str, object]]) -> list[str]:
    lines = [
        "| R symbol | Kind | Python entry point | Status | Milestone | Oracle cases "
        "| Tolerance profile | Known differences |",
        "| --- | --- | --- | --- | --- | ---: | --- | --- |",
    ]
    for capability in capabilities:
        raw_cases = capability["oracle_cases"]
        if not isinstance(raw_cases, list):
            raise TypeError("oracle_cases must be a list")
        cases = cast(list[object], raw_cases)
        profiles = [capability["tolerance_profile"]]
        raw_additional_profiles = capability.get("additional_tolerance_profiles", [])
        if not isinstance(raw_additional_profiles, list):
            raise TypeError("additional_tolerance_profiles must be a list")
        profiles.extend(cast(list[object], raw_additional_profiles))
        lines.append(
            "| "
            + " | ".join(
                (
                    _code(capability["r_symbol"]),
                    _markdown_text(capability["kind"]),
                    _code(capability["python_entry_point"]),
                    _markdown_text(capability["status"]),
                    _markdown_text(capability["milestone"]),
                    str(len(cases)),
                    ", ".join(_code(profile) for profile in profiles),
                    _markdown_text(capability["known_differences"]),
                )
            )
            + " |"
        )
    return lines


def render_compatibility_page() -> str:
    document = _load_compatibility()
    capabilities = _capabilities(document)
    reference = document["reference"]
    if not isinstance(reference, dict):
        raise TypeError("compatibility reference must be an object")
    reference = cast(Mapping[str, object], reference)
    status_counts = Counter(str(item["status"]) for item in capabilities)
    tier_counts = Counter(str(item["tier"]) for item in capabilities)
    evidence_backed = [
        item
        for item in capabilities
        if item["status"] in {"implemented", "experimental"}
    ]

    lines = [
        GENERATED_NOTICE,
        "",
        "# Compatibility",
        "",
        "This page is generated from the authoritative",
        "[`compatibility/rms-8.2.0.yaml`](https://github.com/joshuamyers22/"
        "holocron/blob/main/compatibility/rms-8.2.0.yaml)",
        "manifest. Edit the manifest and run `make docs-generate`; CI rejects a "
        "stale page.",
        "",
        "Holocron makes capability-level claims only. A frozen R oracle baseline is "
        "not",
        "an implementation claim, and an experimental capability is not "
        "production-ready.",
        "",
        "## Reference identity",
        "",
        f"- Package: `{reference['package']}` `{reference['version']}`",
        f"- Source commit: `{reference['commit']}`",
        f"- Namespace SHA-256: `{reference['namespace_sha256']}`",
        f"- Manifest schema: `{document['schema_version']}`",
        f"- Catalogued capabilities: **{len(capabilities)}**",
        "",
        "## Status summary",
        "",
        "| Status | Count | Meaning |",
        "| --- | ---: | --- |",
    ]
    meanings = {
        "implemented": "Implemented and accepted under the capability contract.",
        "experimental": (
            "Implemented narrowly with parity evidence; not production-ready."
        ),
        "mapped": (
            "Mapped to a Python design, without an accepted implementation claim."
        ),
        "unsupported": "Intentionally excluded from the compatibility target.",
        "deferred": "Catalogued for a later phase; no current implementation claim.",
    }
    for status in STATUS_ORDER:
        lines.append(f"| {status} | {status_counts[status]} | {meanings[status]} |")

    lines.extend(
        [
            "",
            "## Evidence-backed experimental surface",
            "",
            "Only these capabilities currently have independent Python implementations "
            "and",
            "oracle-linked parity evidence. Their documented support envelopes remain "
            "narrow.",
            "",
            *_render_capability_table(evidence_backed),
            "",
            "## Complete inventory",
            "",
            "The tables below account for every exported function and registered S3 "
            "method",
            "in the pinned namespace. Counts by tier are "
            + ", ".join(f"{tier}: {tier_counts[tier]}" for tier in TIER_ORDER)
            + ".",
            "",
        ]
    )
    for tier in TIER_ORDER:
        tier_capabilities = [item for item in capabilities if item["tier"] == tier]
        lines.extend(
            [
                f"### Tier {tier} ({len(tier_capabilities)})",
                "",
                *_render_capability_table(tier_capabilities),
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def generated_documents() -> dict[Path, str]:
    documents = {
        path: render_api_page(module_name) for path, module_name in API_MODULES.items()
    }
    documents[ROOT / "docs/compatibility.md"] = render_compatibility_page()
    return documents


def _check_document(path: Path, expected: str) -> bool:
    if not path.is_file():
        print(f"missing generated documentation: {path.relative_to(ROOT)}")
        return False
    actual = path.read_text()
    if actual == expected:
        return True
    print(f"stale generated documentation: {path.relative_to(ROOT)}")
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(ROOT)),
        tofile="generated",
        n=2,
    )
    print("\n".join(list(diff)[:24]))
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if generated pages are stale"
    )
    args = parser.parse_args()
    documents = generated_documents()
    if args.check:
        if not all(
            _check_document(path, content) for path, content in documents.items()
        ):
            raise SystemExit(1)
        print(f"generated documentation verified: {len(documents)} pages")
        return
    for path, content in documents.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"generated documentation updated: {len(documents)} pages")


if __name__ == "__main__":
    main()
